<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork1005-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>


<h3> Get to Know a Numpy Array </h3>


You will use the numpy array <code>A</code> for the following questions.


In [3]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) Find the type of `A` using the function `type()`.


In [4]:
type(A)

numpy.ndarray

<details><summary>Click here for the solution</summary>

```python
type(A)
```

</details>


2) Find the shape of the array:


In [8]:
A.shape

(3, 2)

<details><summary>Click here for the solution</summary>

```python
A.shape
```

</details>


3) Find the type of data in the array:


In [10]:
A.dtype

dtype('int32')

<details><summary>Click here for the solution</summary>

```python
A.dtype
```

</details>


4) Find the second row of the numpy array <code>A</code>:


In [18]:
# this is the array 
print("This is the array",A)

# chose the first row
print("first row: ",A[0])

# second row, the instruction (4.) above say that we need to find the second row, is this A[1]  
print("second row: ",A[1]) #

#third row
print("third row: ",A[2])

[[11 12]
 [21 22]
 [31 32]]
first row:  [11 12]
second row:  [21 22]
third row:  [31 32]


<details><summary>Click here for the solution</summary>

```python
A[1]
```

</details>


<h3>Two Types of Multiplication</h3>


You will use the following numpy arrays for the next questions: 


In [42]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) Multiply array <code>A</code> and <code>B</code>.


In [34]:
C = A*B
C

array([[11,  0],
       [ 0, 22]])

<details><summary>Click here for the solution</summary>

```python
C = A * B
C
```

</details>


2)  Perform matrix multiplication on array <code>A</code> and <code>B</code> (order will not matter in this case).


In [43]:
Z = np.dot(A,B)
Z

array([[11, 12],
       [21, 22]])

<details><summary>Click here for the solution</summary>

```python
Z = np.dot(A,B)
Z
```

</details>


This operation is not possible if the two arrays have different sizes 

In [48]:

A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

try: 
    Z = np.dot(A,B)
    Z
except ValueError:
    print("The shape of arrays it`s not same size: A shape:",A.shape,"B shape: ",B.shape )

The shape of arrays it`s not same size: A shape: (4, 2) B shape:  (3, 3)


<hr>

<h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
